from distutils.core import setup

setup(
    name="mtaa",
    version="1.1",
    description="A package consisting of all Tanzania locations from region to streets in a easy accessible way",
    url="https://github.com/Kalebu/mtaa",
    download_url="https://github.com/Kalebu/mtaa/archive/1.1.tar.gz",
    author="Jordan Kalebu",
    author_email="isaackeinstein@gmail.com",
    license="MIT",
    packages=["mtaa"],
    keywords=[
        "mtaa",
        "python-tanzania",
        "tanzania locations",
        "mtaa python",
        "mtaa package",
        "mtaa python package",
        "all tanzania location",
        "mtaa github",
        "python mtaa",
    ],
    include_package_data=True,
    python_requires=">=3.6",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Build Tools",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
)